services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/khisha.db
  frontend:
    build: .
    environment:
      - VITE_API_BASE=http://localhost:5000/api
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_data:








